mayastorImagesTag: latest
mayastorImagePullPolicy: Always
mayastorCpuCount: "1"
mayastorHugePagesGiB: "1"
mayastorImagesRegistry: ""
mayastorPools:
  - node: "NODE_NAME"
    device: "DEVICE"
# This option is intended for development yamls and motivated by the problem of
# moac that does not update status of msp resource in some cases. Feel free to
# remove when no longer needed.
moacDebug: false

csi:
  nvme:
    # nvme_core module io timeout in seconds
    io_timeout: "30"
    io_timeout_enabled: true

nats:
  cluster:
    enabled: false
  exporter:
    enabled: false
  logging:
    debug: false
    trace: false

etcd:
  ## Kubernetes Cluster Domain
  ##
  clusterDomain: cluster.local
  ## TLS authentication for client-to-server communications
  ## ref: https://etcd.io/docs/current/op-guide/security/
  ##
  client:
    secureTransport: false
  ## TLS authentication for server-to-server communications
  ## ref: https://etcd.io/docs/current/op-guide/security/
  ##
  peer:
    secureTransport: false
  ## Enable persistence using Persistent Volume Claims
  ## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
  ##
  persistence:
    ## If true, use a Persistent Volume Claim. If false, use emptyDir.
    ##
    enabled: false
  ## Set to true if you would like to see extra information on logs
  ##
  debug: false

  ## Pod anti-affinity preset
  ## Ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
  ## Allowed values: soft, hard
  ##
  podAntiAffinityPreset: "hard"
