[patch.crates-io]
h2 = { git = "https://github.com/openebs/h2",  rev = "0.3.3"}
# Nats with the tcp stream timeout fix: CAS-1192
nats = { git = "https://github.com/openebs/nats.rs", rev="main_fixes" }

[profile.dev]
panic = "abort"

[workspace]
members = [
	"csi",
	"devinfo",
	"jsonrpc",
	"mayastor",
	"mbus-api",
	"nvmeadm",
	"rpc",
	"sysfs",
	"composer",
]
