[patch.crates-io]
h2 = { git = "https://github.com/gila/h2", branch = "v0.2.5"}
partition-identity = { git = "https://github.com/openebs/partition-identity.git" }

[workspace]
members = [
	"csi",
	"devinfo",
	"jsonrpc",
	"mayastor",
	"nvmeadm",
	"rpc",
	"sysfs",
]
