[patch.crates-io]
partition-identity = { git = "https://github.com/openebs/partition-identity.git" }
h2 = { git = "https://github.com/openebs/h2", branch = "v0.3.3"}

[profile.dev]
panic = "abort"

[workspace]
members = [
	"csi",
	"devinfo",
	"jsonrpc",
	"mayastor",
	"mbus-api",
	"nvmeadm",
	"sysfs",
	"composer",
]
