[package]
authors = ["Jeffry Molanus <jeffry.molanus@gmail.com>"]
name = "mayastor"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "mayastor"
path = "src/bin/main.rs"

[[bin]]
name = "spdk"
path = "src/bin/spdk.rs"

[[bin]]
name = "initiator"
path = "src/bin/initiator.rs"

[[bin]]
name = "uring-support"
path = "src/bin/uring-support.rs"

[dev-dependencies]
assert_matches = "1.2"
run_script = "*"

[dependencies]
async-task = "3.0"
async-trait = "0.1.36"
bincode = "1.2"
byte-unit = "3.0.1"
bytes = "0.4.12"
clap = "2.33.0"
crc = "1.8.1"
crossbeam = "0.7.3"
crossbeam-sync = "0.0.0"
env_logger = "0.7"
futures = "0.3"
futures-timer = "2.0"
git-version = "0.3"
io-uring = "0.3.4"
ioctl-gen = "0.1.1"
libc = "0.2"
log = "0.4"
nix = "0.16"
once_cell = "1.3.1"
pin-utils = "0.1"
rand = "0.7.3"
rpc = { path = "../rpc"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
signal-hook = "0.1"
snafu = "0.6"
spdk-sys = { path = "../spdk-sys" }
structopt = "0.3.11"
sysfs = { path = "../sysfs"}
tokio = { version = "0.2", features = ["full"]}
tokio-nats = "0.1.0"
url = "2.1"
uuid = { version = "0.7", features = ["v4"] }
tracing = "0.1"
tracing-futures = "0.2.4"
# grpc related

prost = "0.6"
prost-derive = "0.6"
prost-types = "0.6"
tonic = "0.1"
tower = "0.3"
