[package]
authors = ["Jeffry Molanus <jeffry.molanus@gmail.com>"]
name = "mayastor"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "mayastor"
path = "src/bin/main.rs"

[[bin]]
name = "spdk"
path = "src/bin/spdk.rs"

[[bin]]
name = "initiator"
path = "src/bin/initiator.rs"

[dev-dependencies]
assert_matches = "1.2"
run_script = "*"

[dependencies]
bincode = "1.2"
bytes = "0.4.12"
byte-unit = "3.0.1"
clap = "2.33.0"
crc = "1.8.1"
env_logger = "0.7"
futures = "0.3"
futures-timer = "2.0"
git-version = "0.3"
ioctl-gen = "0.1.1"
io-uring = "0.3.4"
libc = "0.2"
log = "0.4"
nix = "0.16"
once_cell = "1.3"
rpc = { path = "../rpc"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
snafu = "0.6"
spdk-sys = { path = "../spdk-sys" }
url = "2.1"
uuid = { version = "0.7", features = ["v4"] }
structopt = "0.2.18"
sysfs = { path = "../sysfs"}
async-task = "1.3.1"
crossbeam = "0.7.3"
pin-utils = "0.1.0-alpha.4"
crossbeam-sync = "0.0.0"
