[package]
authors = ["Jeffry Molanus <jeffry.molanus@gmail.com>"]
name = "mayastor"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "mayastor"
path = "src/bin/main.rs"

[dependencies]
bytes = "0.4.12"
futures-preview = "=0.3.0-alpha.18"
git-version = "0.3.1"
lazy_static = "1.3.0"
libc = "0.2"
log = "0.4.6"
nix = "0.15.0"
num = "0.2"
num-derive = "0.2"
num-traits = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.39"
spdk-sys = { path = "../spdk-sys" }
stderrlog = "0.4.1"
url = "2.1.0"
url_serde = "0.2.0"
uuid = { version = "0.7", features = ["v4"] }
rpc = { path = "../rpc"}
sysfs = { path = "../sysfs"}
