[package]
authors = ["Jeffry Molanus <jeffry.molanus@gmail.com>"]
name = "mayastor"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "mayastor"
path = "src/bin/main.rs"

[[bin]]
name = "spdk"
path = "src/bin/spdk.rs"

[dependencies]
bincode = "1.2.0"
bytes = "0.4.12"
crc = "1.8.1"
env_logger = "0.7"
futures-preview = "=0.3.0-alpha.19"
futures-timer = "0.4.0"
git-version = "0.3.1"
ioctl-gen = "0.1.1"
lazy_static = "1.3.0"
libc = "0.2"
log = "0.4.6"
nix = "0.15.0"
rpc = { path = "../rpc"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.39"
spdk-sys = { path = "../spdk-sys" }
stderrlog = "0.4.1"
sysfs = { path = "../sysfs"}
url = "2.1.0"
url_serde = "0.2.0"
uuid = { version = "0.7", features = ["v4"] }
