apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: mayastor
  labels:
    openebs/engine: mayastor
spec:
  selector:
    matchLabels:
      app: mayastor
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mayastor
    spec:
      hostNetwork: true
      # To resolve services in the namespace
      {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName | quote }}
      {{- end }}
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        {{- range .Values.nodeSelector -}}
        {{ . | toYaml | nindent 8 }}
        {{- end }}
      affinity: {{ .Values.affinity | toYaml | nindent 8 }}
      initContainers:
      - name: registration-probe
        image: busybox:latest
        command: ['sh', '-c', 'until nc -vz core 50051; do echo "Waiting for registration service..."; sleep 1; done;']
      - name: etcd-probe
        image: busybox:latest
        command: ['sh', '-c', 'until nc -vz {{ include "etcdEndpoint" . }} 2379; do echo "Waiting for etcd..."; sleep 1; done;']
      {{- if .Values.mayastorExtraInitContainers -}}
      {{ tpl (.Values.mayastorExtraInitContainers | toYaml) . | nindent 6 }}
      {{- end }}
      containers:
      - name: mayastor
        image: {{ include "mayastorImagesPrefix" . }}{{ .Values.mayastorImage }}:{{ .Values.mayastorImagesTag }}
        imagePullPolicy: {{ .Values.mayastorImagePullPolicy }}
        env:
        - name: RUST_LOG
          value: info,mayastor={{ .Values.mayastorLogLevel }}
        - name: NVMF_TCP_MAX_QUEUE_DEPTH
          value: "32"
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        args:
        # The -l argument accepts cpu-list. Indexing starts at zero.
        # For example -l 1,2,10-20 means use core 1, 2, 10 to 20.
        # Note: Ensure that the CPU resources are updated accordingly.
        #       If you use 2 CPUs, the CPU: field should also read 2.
        - "-N$(MY_NODE_NAME)"
        - "-g$(MY_POD_IP)"
        - "-Rhttps://core:50051"
        - "-y/var/local/mayastor/config.yaml"
        - "-l{{ include "mayastorCpuSpec" . }}"
        - "-p{{- include "etcdEndpoint" . -}}"
        command:
        - mayastor
        securityContext:
          privileged: true
        volumeMounts:
        - name: device
          mountPath: /dev
        - name: udev
          mountPath: /run/udev
        - name: dshm
          mountPath: /dev/shm
        - name: configlocation
          mountPath: /var/local/mayastor/
        {{- if .Values.mayastorExtraVolumeMounts -}}
        {{ .Values.mayastorExtraVolumeMounts | toYaml | nindent 8 }}
        {{- end }}
        resources:
          # NOTE: Each container must have mem/cpu limits defined in order to
          # belong to Guaranteed QoS class, hence can never get evicted in case of
          # pressure unless they exceed those limits. limits and requests must be the same.
          limits:
            cpu: "{{ .Values.mayastorCpuCount }}"
            memory: "1Gi"
            hugepages-2Mi: "{{ max .Values.mayastorHugePagesGiB 2 }}Gi"
          requests:
            cpu: "{{ .Values.mayastorCpuCount }}"
            memory: "1Gi"
            hugepages-2Mi: "{{ max .Values.mayastorHugePagesGiB 2 }}Gi"
        ports:
        - containerPort: 10124
          protocol: TCP
          name: mayastor
      volumes:
      - name: device
        hostPath:
          path: /dev
          type: Directory
      - name: udev
        hostPath:
          path: /run/udev
          type: Directory
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "1Gi"
      - name: hugepage
        emptyDir:
          medium: HugePages
      - name: configlocation
        hostPath:
          path: {{ .Values.mayastorConfigLocation | quote }}
          type: DirectoryOrCreate
      {{- if .Values.mayastorExtraVolumes -}}
      {{ .Values.mayastorExtraVolumes | toYaml | nindent 6 }}
      {{- end }}
