apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: mayastor
  name: mayastor
  labels:
    openebs/engine: mayastor
spec:
  selector:
    matchLabels:
      app: mayastor
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mayastor
    spec:
      hostNetwork: true
      # To resolve services from mayastor namespace
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        openebs.io/engine: mayastor
        kubernetes.io/arch: amd64
      initContainers:
      - name: message-bus-probe
        image: busybox:latest
        command: ['sh', '-c', 'until nc -vz nats 4222; do echo "Waiting for message bus..."; sleep 1; done;']
      containers:
      - name: mayastor
        image: {{ include "mayastorImagesPrefix" . }}mayadata/mayastor:{{ .Values.mayastorImagesTag }}
        imagePullPolicy: Always
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: IMPORT_NEXUSES
          value: "false"
        args:
        # In order to select what cores mayastor should be running on, a mask or a list can be specified.
        # For example: -m 0x1 will tell mayastor to only use one core which is equivalent to -l 1
        # Using a mask of 0x3 will use the first 2 cores, which is equivalent to -l 1-2
        #
        # The -l argument supports ranges to be able to do the same as passing a mask for example:
        # -l 1,2,10-20 means use core 1, 2, 10 to 20
        #
        # Note:
        # 1. When both -m and -l are specified the -l argument is takes precedence.
        # 2. Ensure that the CPU resources are updated accordingly. If you use 2 CPUs, the CPU: field should also read 2.
        - "-N$(MY_NODE_NAME)"
        - "-g$(MY_POD_IP)"
        - "-nnats"
        - "-y/var/local/mayastor/config.yaml"
        - "-m0x3"
        securityContext:
          privileged: true
        volumeMounts:
        - name: device
          mountPath: /dev
        - name: udev
          mountPath: /run/udev
        - name: dshm
          mountPath: /dev/shm
        - name: configlocation
          mountPath: /var/local/mayastor/
        - name: config
          mountPath: /var/local/mayastor/config.yaml
        resources:
          # NOTE: Each container must have mem/cpu limits defined in order to
          # belong to Guaranteed QoS class, hence can never get evicted in case of
          # pressure unless they exceed those limits. limits and requests must be the same.
          limits:
            cpu: "2"
            memory: "500Mi"
            hugepages-2Mi: "1Gi"
          requests:
            cpu: "2"
            memory: "500Mi"
            hugepages-2Mi: "1Gi"
        ports:
        - containerPort: 10124
          protocol: TCP
          name: mayastor
      volumes:
      - name: device
        hostPath:
          path: /dev
          type: Directory
      - name: udev
        hostPath:
          path: /run/udev
          type: Directory
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "1Gi"
      - name: hugepage
        emptyDir:
          medium: HugePages
      - name: configlocation
        hostPath:
          path: /var/local/mayastor/
          type: DirectoryOrCreate
      - name: config
        hostPath:
          path: /var/local/mayastor/config.yaml
          type: FileOrCreate
