[package]
name = "devinfo"
version = "1.0.0"
authors = ["Jeffry Molanus <jeffry.molanus@gmail.com>"]
edition = "2018"

[dependencies]
snafu = "0.6.10"
udev = "0.6.2"
url = "2.2.2"
uuid = { version = "0.8.2", features = ["v4"] }
[build-dependencies]
bindgen = "0.59.1"
