[package]
authors = ["Jan Kryl <jan.kryl@mayadata.io>", "Jeffry Molanus <jeffry.molanus@mayadata.io"]
name = "csi"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "mayastor-agent"
path = "src/server.rs"

[[bin]]
name = "mayastor-client"
path = "src/client.rs"

[build-dependencies]
tonic-build = "0.1.0-alpha.3"
prost-build = "0.5.0"

[dependencies]
async-stream = "0.1.2"
bytes = "0.4"
bytesize = "1.0.0"
chrono = "0.4.9"
clap = "2.32"
env_logger = "0.6"
futures-preview = "=0.3.0-alpha.19"
futures-util-preview = "=0.3.0-alpha.19"
git-version = "0.3.1"

glob = "*"
http = "0.1.19"
http-body = "=0.2.0-alpha.3"
jsonrpc = { path = "../jsonrpc" }
libc = "0.2"
log = "0.4"
loopdev = "*"
nix = "*"
proc-mounts = "0.2.2"
prost = "0.5"
prost-derive = "0.5"
prost-types = "0.5"
rpc = { path = "../rpc" }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0.98"
serde_json = "1.0.36"
sys-mount = "1.2.0"
sysfs = { path = "../sysfs"}
tokio = "0.2.0-alpha.6"
run_script = "*"
tokio-net = "0.2.0-alpha.6"
tonic = "0.1.0-alpha.3"
tower = "=0.3.0-alpha.2"
tracing-log = {version = "0.1.1", features = ["env_logger"] }
[dependencies.blkid]
branch = "blkid-sys"
git = "https://github.com/openebs/blkid"

