---
{{ if and .Values.etcd.enabled .Values.etcd.persistence.enabled (eq .Values.etcd.persistence.storageClass "manual") }}
{{- range $index, $end := until (.Values.etcd.replicaCount | int) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: {{ $.Release.Namespace }}
  name: etcd-volume-{{ $index }}
  labels:
    statefulset.kubernetes.io/pod-name: mayastor-etcd-{{ $index }}
spec:
  storageClassName: manual
  # You must also delete the hostpath on the node
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: {{ $.Values.etcd.persistence.size | quote }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/local/mayastor/etcd/pod-{{ $index }}"
---
{{- end }}
{{- end }}
