name: "Mayastor tests"
on:
  pull_request:
    paths-ignore:
      - 'csi/moac/**'
      - 'doc/**'
jobs:
  Build:
    name: Build and run tests
    runs-on: self-hosted
    container:
      image: docker.io/mayadata/ms-buildenv:nix
      options: --privileged -v /dev:/dev -v /bin:/host/bin -v /lib/modules:/lib/modules
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: cachix/cachix-action@v5
        with:
          name: mayastor
          skipNixBuild: true
      - run: ln -s /host/bin/kmod /bin/modprobe
      - run: /bin/modprobe nbd
      - run: /bin/modprobe xfs
      - run: echo 4096 | tee /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
      - run: rm mayastor/.cargo/config
      - run: cargo build --all
      # cargo test cases
      - run: ( cd jsonrpc && cargo test )
      - run: ( cd nvmeadm && cargo test )
      - run: ( cd mayastor && cargo test -- --test-threads=1 )
      
      # mocha test caes
      - run: ( cd mayastor-test && npm install && ./node_modules/mocha/bin/mocha test_cli.js )
      - run: ( cd mayastor-test && ./node_modules/mocha/bin/mocha test_replica.js )
      - run: ( cd mayastor-test && TEST_PORT=10125 ./node_modules/mocha/bin/mocha test_replica.js )
      - run: ( cd mayastor-test && ./node_modules/mocha/bin/mocha test_csi.js )
      - run: ( cd mayastor-test && ./node_modules/mocha/bin/mocha test_nexus.js )
      - run: ( cd mayastor-test && TEST_PORT=10125 ./node_modules/mocha/bin/mocha test_nexus.js )
      - run: ( cd mayastor-test && ./node_modules/mocha/bin/mocha test_rebuild.js )
      - run: ( cd mayastor-test && TEST_PORT=10125 ./node_modules/mocha/bin/mocha test_rebuild.js )
      
      # construct images
      - run: nix-build -A mayastorImage -o /tmp/mayastorImage
      - run: nix-build -A mayastorCSIImage -o /tmp/mayastorCSIImage
