name: "CI-basic"
on:
  pull_request:
  push:
jobs:
  Build:
    runs-on: ubuntu-latest
    container: docker://mayadata/ms-buildenv:buildah
    steps:
      - uses: actions/checkout@master
      - run: cargo build --all

  Clippy:
    runs-on: ubuntu-latest
    container: docker://mayadata/ms-buildenv:buildah
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
