name: "Mayastor tests"
on:
  pull_request:
    paths-ignore:
  push:
    branches:
      - develop
jobs:
  Build_and_run_cargo:
    name: Build and run cargo tests
    runs-on: self-hosted
    timeout-minutes: 20
    container:
      image: docker.io/mayadata/ms-buildenv:latest
      options: --privileged -v /dev:/dev -v /bin:/host/bin -v /lib/modules:/lib/modules
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          # this does not pin the compiler version
          toolchain: stable
      - run: ln -s /host/bin/kmod /bin/modprobe
      - run: /bin/modprobe nbd
      - run: /bin/modprobe xfs
      - run: /bin/modprobe nvme_tcp
      - run: echo 8192 | tee /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
      - run: rm mayastor/.cargo/config
      - run: rm nvmeadm/.cargo/config
      - run: cargo build --all
      - run: ( cd jsonrpc && cargo test )
      - run: ( cd mayastor && cargo test -- --test-threads=1 )
      - run: mkdir ./target/debug/github-artifacts/
      - run: ( cd ./target/debug/ && cp mayastor mayastor-client mayastor-agent spdk initiator mctl github-artifacts/ )
      - run: ( cd nvmeadm && cargo test )
      - uses: actions/upload-artifact@v2
        with:
          name: mayastor
          path: ./target/debug/github-artifacts
  Build_and_test_moac:
    name: Build and run moac tests
    runs-on: ubuntu-latest
    container:
      image: docker.io/mayadata/ms-buildenv:latest
    steps:
      - uses: actions/checkout@v2
      # npm prepare is normally done by npm install but not if run as a root
      - run: cd csi/moac && npm install && npm run-script prepare
      - run: cd csi/moac && npm test
  Test_mayastor_with_mocha:
    needs: Build_and_run_cargo
    name: Run mocha tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: mayastor
          path: ./target/debug
      - run: ( sudo modprobe nbd )
      - run: ( sudo modprobe xfs )
      - run: ( sudo modprobe nvme_tcp )
      # In line below change 2048 to 8192 if running on self-hosted instead of ubuntu-latest.
      - run: ( echo 2048 | sudo tee /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages )
      - run: ( /usr/bin/docker create --name mochaTest --workdir /__w/Mayastor/Mayastor --network host --privileged -v /dev:/dev -v /:/host  --cpus 2 -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work":"/__w" --entrypoint "tail" docker.io/mayadata/ms-buildenv:latest "-f" "/dev/null" )
      - run: ( /usr/bin/docker start mochaTest )
      - run: ( /usr/bin/docker exec mochaTest /bin/sh -c 'printf "#!/usr/bin/env bash\nchroot /host /usr/bin/env -i PATH=\"/sbin:/bin:/usr/bin\" iscsiadm \"\$@\"\n" > /bin/mayastor-iscsiadm && chmod +x /bin/mayastor-iscsiadm' )
      - run: ( /usr/bin/docker exec mochaTest /bin/sh -c "cd target/debug/ && chmod a+x mayastor mayastor-client mayastor-agent spdk initiator mctl" )
      - run: ( /usr/bin/docker exec mochaTest /bin/sh -c "cd mayastor-test && npm install" )
      - run: ( /usr/bin/docker exec mochaTest /bin/sh -c "cd mayastor-test && ./node_modules/mocha/bin/mocha test_csi.js" )
      - run: ( /usr/bin/docker exec mochaTest /bin/sh -c "cd mayastor-test && ./node_modules/mocha/bin/mocha test_cli.js" )
      - run: ( /usr/bin/docker exec mochaTest /bin/sh -c "cd mayastor-test && ./node_modules/mocha/bin/mocha test_replica.js" )
      - run: ( /usr/bin/docker exec mochaTest /bin/sh -c "cd mayastor-test && ./node_modules/mocha/bin/mocha test_nexus.js" )
      - run: ( /usr/bin/docker exec mochaTest /bin/sh -c "cd mayastor-test && ./node_modules/mocha/bin/mocha test_rebuild.js" )
      - run: ( /usr/bin/docker rm --force mochaTest )
