name: "Build"
on:
  push:
    branches:
      - staging
      - trying
env:
  GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GH_PACKAGES }}
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    container: docker://mayadata/ms-buildenv:nix
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - run: cargo build --all
  Clippy:
    name: Clippy
    runs-on: ubuntu-latest
    container: docker://mayadata/ms-buildenv:nix
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
      - uses: actions-rs/clippy-check@v1.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all --all-targets -- -D warnings
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v7
      - run: nix-build -A mayastorImage
  ms-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v7
      - run: nix-build -A ms-buildenv
