name: "Image"
on:
  pull_request:
    paths-ignore:
      #- 'doc/**'
  push:
    branches:
      - develop
jobs:
  MOAC:
    name: Build MOAC image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
      - uses: cachix/cachix-action@v5
        with:
          name: mayastor
          skipNixBuild: true
      - run: nix-build -A images.moac-image -o /tmp/moac-image
      - uses: actions/upload-artifact@v2
        with:
          name: mayastor-moac-image
          path: /tmp/moac-image
        if: ${{ github.event_name != 'pull_request' }}
  Mayastor:
    name: Build Mayastor image
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v10
      - uses: cachix/cachix-action@v5
        with:
          name: mayastor
          skipNixBuild: true
      - run: nix-build -A images.mayastor-image -o /tmp/mayastorImage
