name: "Nix Workflow Tests"
on:
  pull_request:
    paths-ignore:
  push:
    branches:
      - develop
jobs:
  main:
    name: Run Nix Tests
    runs-on: self-hosted
    timeout-minutes: 30
    defaults:
      run:
        working-directory: $GITHUB_WORKSPACE/repo-under-test
    steps:
      - uses: actions/checkout@v2
        with:
          path: $GITHUB_WORKSPACE/repo-under-test # Checkout with a new path, to avoid permissions on the runner.
      - run: modprobe kvm_intel nested=1 # Could do this once persistently on the runner.
      - run: echo "::set-env name=NIX_PATH::/home/gila/.nix-defexpr/channels"
      - run: bash -c "if [ -L ./result ]; then nix-store --delete ./result --ignore-liveness; fi"
      - run: nix-build ./nix/test -A rebuild
      - run: nix-build ./nix/test -A fio_nvme_basic
      - run: nix-build ./nix/test -A nvmf_distributed
      - run: nix-build ./nix/test -A nvmf_ports
      - run: nix-build ./nix/test -A child_status
      - run: nix-build ./nix/test -A validation
