name: "Lint and style Checks"
on:
  pull_request:
jobs:
  Clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: cachix/install-nix-action@v10
      - run: nix-env -f shell.nix -i -A 'buildInputs'
      - uses: actions-rs/toolchain@master
        with:
          toolchain: nightly-2020-06-21
          components: clippy
      - uses: actions-rs/clippy-check@v1.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all --all-targets -- -D warnings
  Semistandard:
    name: SemiStandard
    runs-on: ubuntu-latest
    container:
      image: docker.io/mayadata/ms-buildenv:latest
    steps:
      - uses: actions/checkout@master
      - run: git ls-files | grep '\.js$' | xargs -r ./scripts/js-check.sh
        shell: bash
