name: "Lint and style Checks"
on:
  pull_request:
  push:
jobs:
  Clippy:
    name: Clippy
    runs-on: ubuntu-latest
    container:
      image: docker.io/mayadata/ms-buildenv:gila
    steps:
      - uses: actions/checkout@master
      - run: nix-shell --run "cargo fmt --all -- --check"
      - run: nix-shell --run "cargo clippy --all-targets -- -D warnings"
  Semistandard:
    name: SemiStandard
    runs-on: ubuntu-latest
    container:
      image: docker.io/mayadata/ms-buildenv:latest
    steps:
      - uses: actions/checkout@master
      - run: git ls-files | grep '\.js$' | xargs -r ./scripts/js-check.sh
        shell: bash
