name: "Lint and style Checks"
on:
  pull_request:
jobs:
  Clippy:
    name: Clippy
    runs-on: ubuntu-latest
    container:
      image: docker.io/mayadata/ms-buildenv:latest
    steps:
      - uses: actions/checkout@master
      - run: nix-shell --run "cargo fmt --all -- --check"
      - run: nix-shell --run "cargo clippy --all-targets -- -D warnings"
  Semistandard:
    name: SemiStandard
    runs-on: ubuntu-latest
    container:
      image: docker.io/node/node:12
    steps:
      - uses: actions/checkout@master
      - run: ./scripts/js-check.sh
